# -*- mode: python ; coding: utf-8 -*-
block_cipher = None

a = Analysis(
    ['run.py'],
    pathex=['.', '..'],
    binaries=[],
    datas=[],
    hiddenimports=[
        'main',
        'config',
        'agent', 'agent.reasonix', 'agent.codegraph',
        'rag', 'rag.document_parser', 'rag.vector_store', 'rag.table_recognizer', 'rag.llm_wiki',
        'rag.pdf_table_recognition', 'rag.finance_qa',
        'skills', 'skills.skill_manager', 'skills.markdown_report_skill', 'skills.word_skill',
        'skills.ppt_skill',
        'models',
        'tablenet', 'tablenet.engine',
        'uvicorn.logging', 'uvicorn.loops.auto',
        'uvicorn.protocols.http.auto', 'uvicorn.protocols.websockets.auto',
        'openai', 'pydantic',
        'docx', 'pptx', 'openpyxl',
        'PyPDF2', 'PIL', 'pandas', 'numpy',
        'fitz', 'pdfplumber', 'httpx',
        'multipart', 'aiofiles',
    ],
    excludes=[
        'matplotlib', 'tkinter', 'unittest', 'setuptools', 'pip', 'distutils',
        'torch', 'tensorflow', 'tensorboard', 'keras',
        'torchvision', 'torchaudio',
        'gradio', 'streamlit', 'dash',
        'cv2', 'opencv',
        'transformers', 'datasets', 'sentence_transformers',
        'sympy', 'numba', 'dask', 'numba',
        'plotly', 'bokeh', 'altair',
        'pyarrow', 'pyspark',
        'beautifulsoup4', 'selenium',
        'h5py', 'grpc', 'zmq', 'pyzmq',
        'jedi', 'parso', 'pygments',
        'tornado', 'prompt_toolkit',
        'pygame',
        'scipy', 'sklearn', 'scikit-learn',
        'notebook', 'nbformat', 'nbconvert',
        'pytz', 'dateutil', 'six',
        'bcrypt',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts, a.binaries, a.zipfiles, a.datas, [],
    name='backend',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
